### PR TITLE
💄 update gitlab logo

### PR DESCRIPTION
**Pull request by pesader**
Gitlab has changed its logo (and Font Awesome has already been updated to reflect that change), so replace old logo with new one.

image

Thanks for developing Lynx! 🐱🔗

### CODE REVIEW

**Comment by jpanther** [comment]
Thanks for the updated icon however this new file is not in keeping with the rest of the SVG icons. Could you please ensure it conforms to the same standard and includes items such as `currentColor` inside the `path` tag?

**Comment by pesader** [comment]
Hi, thank you for reviewing my contribution! I updated my PR with the changes you requested.

**Comment by pesader** [comment]
@jpanther Hi! This PR has been marked as stale and will be closed automatically soon. Could you please review it?

**Comment by jpanther** [comment]
Thanks but I still don't see these changes? Have you pushed them to the PR?

**Comment by pesader** [comment]
My bad, looks like I didn't push 😅 

Thanks for updating though :)

**Pull request closed without merging**
