### PR TITLE
Add Credly

### PR DESCRIPTION
**Pull request by rwehe**
Credly shows digital credentials
It would be nice to have in the main template
https://info.credly.com/

### CODE REVIEW

**Comment by jpanther** [comment]
Thanks for the suggestion, however the icons in Lynx come from FontAwesome and the SVG assets you have provided look like a full logo rather than an icon. Please update your PR with assets that are in keeping with the overall design of the theme.

**Comment by rwehe** [comment]
Looks like there’s an open request for the icon…
https://github.com/FortAwesome/Font-Awesome/issues/15734

No other possibilities to implement this without an official Font Awesome update or Pro Acct to make one?

**Comment by jpanther** [comment]
Given there's not official FontAwesome one, I'm happy to look at other options if you can find an SVG that is in keeping with the existing icons in the theme.

**Comment by rwehe** [comment]
first attempt at normalizing it to look more like the theme
https://github.com/rwehe/lynx/blob/dev/assets/icons/credly.svg
They don't really have a block logo like the other ones in the icons folder so I think it's going to have to be the entire name as the logo

**Comment by jpanther** [comment]
> I think it's going to have to be the entire name as the logo

Thanks, however that is still not in keeping with the theme. It's obviously fine for you to use this type of logo in your own project but I don't wish to include it in the theme package as it will disrupt the overall design language. One of the reasons for using FontAwesome for all the current assets is to keep a consistent design that is simple and easy for people to use.

**Comment by rwehe** [comment]
PR declined due to logo incompatibility

**Pull request closed without merging**
